// ╔══════════════════════════════════════════════════════╗
// ║  Generated by MasaIni_Stamper.py                   ║
// ║  #included by MasaIni_LyricsVideo.ino              ║
// ╚══════════════════════════════════════════════════════╝

#pragma once

struct Lyric {
  const char* line1;        // first display row
  const char* line2;        // second row, empty for single-line
  unsigned long startMs;    // ms from song start
  unsigned long endMs;
};

#define SONG_DURATION_MS  (178573UL)

const Lyric lyrics[] = {
  {"Semua kata", "yang terucap", 99440UL, 102114UL},
  {"Semua tertuju", "padamu, oh", 102114UL, 110742UL},
  {"Semua arah", "yang ku tempuh", 110742UL, 113450UL},
  {"Semua tertuju", "padamu,", 113450UL, 119252UL},
  {"ho-oh-oh", "", 119252UL, 122132UL},
  {"Kau adalah", "semua jawaban", 122132UL, 127086UL},
  {"Dari doa yang", "kupanjatkan", 127086UL, 132754UL},
  {"Dengan hadirmu", "di hidupku", 132754UL, 137855UL},
  {"Sudah ku", "merasa cukup", 137855UL, 144607UL},
  {"Hati ini telah", "menetapkan", 144607UL, 150347UL},
  {"Engkau sosok yang", "'kan menemaniku", 150347UL, 156799UL},
  {"Di masa ini,", "", 156799UL, 158881UL},
  {"Di masa nanti,", "", 158881UL, 161221UL},
  {"dan masa", "indah lainnya", 161221UL, 167913UL},
  {"Di masa ini,", "", 167913UL, 170237UL},
  {"masa nanti", "", 170237UL, 172573UL},
  {"Dan masa", "indah lainnya", 172573UL, 176573UL},
};
const int NUM_LYRICS = sizeof(lyrics) / sizeof(Lyric);
